const works_library = {
    'tetris_web': {
        'title': 'TETRIS GAME',
        'image': './assets/img/tetrisweb.png',
        'image2': './assets/img/tetrisweb2.png',
        'image3': './assets/img/tetrisweb3.png',
        'explain': [
                    '',
                    'jQueryの勉強目的で作ったテトリスゲームをDjangoでWebアプリケーション化しました。',
                    'ブロックの落下や揃ったら消える処理などはjavascriptですべて一から実装しています。',
                    'サーバ側では、ユーザIDとブロックの落下数をDBに登録し、ネット上のユーザ同士でランキングを競えるようにしました。',
                    '',
                    '・javascript(jQuery)・python(Django)・Postgres・gunicorn・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/oceantako/TETRIS_WEB',
        'link': 'http://ryo-ryo-taro.com/tetris/login'
    },
    'team_portal': {
        'title': 'Team Portal',
        'image': './assets/img/teamportal.png',
        'image2': './assets/img/teamportal2.png',
        'image3': './assets/img/teamportal3.png',
        'explain': [
                    '',
                    'しばらくの間、SEの友人たちと開催していた勉強会(?)で友人たちが作った成果物を共有するためのサイトを自作してみました。',
                    '作成中に勉強会が自然消滅してしまい、結局成果物登録をしているのは私だけの状態です。',
                    '画面側はbootstrapを使用して作成しました。bootstrap勉強始めたての頃なのでＵＩはなんだか微妙です。',
                    'バックエンドはDjangoで実装しています。',
                    '画像ファイルやソースコードをアップロードしたり、リンクを登録することが可能です。',
                    '',
                    '・bootstrap・javascript(jQuery)・python(Django)・Postgres・gunicorn・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': 'https://github.com/oceantako/team_portal',
        'link': 'http://153.127.11.145:8080/works/works_init'
    },
    'my_portfolio': {
        'title': 'Portforlio',
        'image': './assets/img/portfolio1.png',
        'image2': './assets/img/portfolio2.png',
        'image3': './assets/img/portfolio3.png',
        'explain': [
                    '',
                    'このサイトです。主にbootstrapを使用して作成しています。',
                    '大枠はインターネット上のテンプレートをもとにし、細部はbootstrapのコンポーネントやライブラリを用いてカスタマイズしています。',
                    '携帯で見てもPCでも見ても表示が崩れないレスポンシブデザインを意識して作成しました。',
                    '動く背景はhtml canvasにjavascriptでアニメーションを描画しています。',
                    'アニメーションの基礎となるソースコードをchatgptに作成してもらい、カスタマイズしました。',
                    '',
                    '・bootstrap・javascript(jQuery)・nginx・github',
                    'deploy → sakuraVPS',
                    ].join('<br>'),
        'github': '',
        'link': ''
    },
    'othello': {
        'title': 'othello',
        'image': './assets/img/othello.png',
        'image2': './assets/img/othello2.png',
        'image3': './assets/img/othello3.png',
        'explain': [
                    '',
                    '社会人2年目くらいの時に作ったオセロゲームです。githubからダウンロードして遊んでください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/oceantako/othello',
        'link': 'https://github.com/oceantako/othello'
    },
    'maze': {
        'title': 'maze',
        'image': './assets/img/maze.png',
        'image2': './assets/img/maze2.png',
        'image3': './assets/img/maze3.png',
        'explain': [
                    '',
                    'n*n の迷路をランダムに自動生成するjavascriptです。動かす場合はgithubからダウンロードしてください。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/oceantako/meiro_game',
        'link': 'https://github.com/oceantako/meiro_game'
    },
    'typing': {
        'title': 'typing',
        'image': './assets/img/typing.png',
        'image2': './assets/img/typing2.png',
        'image3': './assets/img/typing3.png',
        'explain': [
                    '',
                    'かなり昔に作ったシンプルなタイピングゲームです。githubからダウンロードして遊べます。',
                    '',
                    '',
                    '',
                    '',
                    '',
                    '・javascript(jQuery)・',
                    '',
                    ].join('<br>'),
        'github': 'https://github.com/oceantako/TypingGame',
        'link': 'https://github.com/oceantako/TypingGame'
    },
}